'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend, Cell } from 'recharts';
import { supabase } from '@/lib/supabase';

interface Falha { id:string|number; equipamento:string; sintoma:string; solucao:string; criado_em:string; aprovado:boolean; tipo_parada?:'nao_programada'|'programada'|'sem_parada'; falha_em?:string; retorno_em?:string; }
const duracao=(a?:string,b?:string)=>{ if(!a||!b)return 0; const h=(new Date(b).getTime()-new Date(a).getTime())/3600000; return h>0?h:0; };
const fmt=(h:number)=>{const m=Math.round(h*60);return `${Math.floor(m/60)}h ${String(m%60).padStart(2,'0')}min`;};
const CORES=['#3b82f6','#ef4444','#f59e0b','#10b981','#8b5cf6','#06b6d4','#ec4899','#84cc16','#f97316','#14b8a6'];

export default function Dashboard(){
 const router=useRouter(); const [falhas,setFalhas]=useState<Falha[]>([]); const [loading,setLoading]=useState(true);
 const [periodo,setPeriodo]=useState('todos'); const [equipamento,setEquipamento]=useState('todos'); const [tipo,setTipo]=useState('todos');
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){router.push('/login');return;}const {data:ok}=await supabase.rpc('is_supervisor');if(!ok){router.push('/');return;}const {data}=await supabase.from('falhas').select('*').order('criado_em',{ascending:true});setFalhas(data||[]);setLoading(false);})();},[router]);
 const equipamentos=useMemo(()=>Array.from(new Set(falhas.map(f=>f.equipamento?.trim()).filter(Boolean))).sort(),[falhas]);
 const lista=useMemo(()=>falhas.filter(f=>{if(equipamento!=='todos'&&f.equipamento?.trim()!==equipamento)return false;if(tipo!=='todos'&&(f.tipo_parada||'nao_informado')!==tipo)return false;if(periodo!=='todos'){const d=new Date();d.setDate(d.getDate()-Number(periodo));if(new Date(f.criado_em)<d)return false;}return true;}),[falhas,periodo,equipamento,tipo]);
 const d=useMemo(()=>{const eq:Record<string,{ocorrencias:number;downtime:number;naoProgramadas:number;comTempo:number}>={};const meses:Record<string,{mes:string;ordem:string;ocorrencias:number;downtime:number}>={};const sint:Record<string,number>={'Vazamentos / Fugas':0,'Quebras / Trincas':0,'Vibração / Ruído':0,'Aquecimento':0,'Alarmes':0,'Falha Geral / Erro':0,'Outros':0};const acao:Record<string,number>={'Substituição de Peças':0,'Reparo / Recuperação':0,'Ajuste / Calibragem':0};let downtime=0,np=0,comTempo=0;
 lista.forEach(f=>{const nome=f.equipamento?.trim()||'Desconhecido';eq[nome]??={ocorrencias:0,downtime:0,naoProgramadas:0,comTempo:0};eq[nome].ocorrencias++;const h=f.tipo_parada==='nao_programada'&&f.falha_em&&f.retorno_em?duracao(f.falha_em,f.retorno_em):0;if(f.tipo_parada==='nao_programada'){np++;eq[nome].naoProgramadas++;}if(h>0){downtime+=h;comTempo++;eq[nome].downtime+=h;eq[nome].comTempo++;}
 const x=new Date(f.criado_em),ordem=`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`,mes=x.toLocaleDateString('pt-BR',{month:'short',year:'2-digit'}).replace('.','');meses[ordem]??={mes,ordem,ocorrencias:0,downtime:0};meses[ordem].ocorrencias++;meses[ordem].downtime+=h;
 const s=(f.sintoma||'').toLowerCase();if(s.includes('vazamento')||s.includes('fuga'))sint['Vazamentos / Fugas']++;else if(s.includes('quebra')||s.includes('trinca')||s.includes('ruptura'))sint['Quebras / Trincas']++;else if(s.includes('vibra')||s.includes('ruído')||s.includes('barulh'))sint['Vibração / Ruído']++;else if(s.includes('aqueciment')||s.includes('temperatura'))sint['Aquecimento']++;else if(s.includes('alarme')||s.includes('aviso')||s.includes('warning'))sint['Alarmes']++;else if(s.includes('falha')||s.includes('erro'))sint['Falha Geral / Erro']++;else sint['Outros']++;
 const sol=(f.solucao||'').toLowerCase();if(sol.includes('substituição')||sol.includes('substituir')||sol.includes('troca'))acao['Substituição de Peças']++;else if(sol.includes('reparo')||sol.includes('conserto')||sol.includes('recupera'))acao['Reparo / Recuperação']++;else acao['Ajuste / Calibragem']++;});
 const ranking=Object.entries(eq).map(([nome,v])=>({nome,...v,mttr:v.comTempo?v.downtime/v.comTempo:0})).sort((a,b)=>b.ocorrencias-a.ocorrencias);
 return {downtime,np,mttr:comTempo?downtime/comTempo:0,ranking,meses:Object.values(meses).sort((a,b)=>a.ordem.localeCompare(b.ordem)),sintomas:Object.entries(sint).map(([nome,valor])=>({nome,valor})),acoes:Object.entries(acao).map(([nome,valor])=>({nome,valor}))};},[lista]);
 if(loading)return <main className="min-h-screen bg-gray-900 text-white flex items-center justify-center">Carregando dashboard...</main>;
 const top=d.ranking.slice(0,10),topDt=[...d.ranking].sort((a,b)=>b.downtime-a.downtime).slice(0,10);
 return <main className="min-h-screen bg-gray-900 text-white p-4 sm:p-6"><div className="max-w-7xl mx-auto space-y-6">
 <header className="bg-gray-800 border border-gray-700 rounded-xl p-5 flex flex-col md:flex-row justify-between gap-4"><div><h1 className="text-2xl font-bold text-yellow-400">📊 Dashboard de Manutenção</h1><p className="text-sm text-gray-400">Indicadores e tendências das ocorrências registradas.</p></div><div className="flex gap-2"><Link href="/supervisor" className="bg-gray-700 px-4 py-2 rounded-lg text-sm">Painel do Supervisor</Link><Link href="/" className="bg-gray-700 px-4 py-2 rounded-lg text-sm">Início</Link></div></header>
 <section className="grid md:grid-cols-3 gap-3 bg-gray-800 border border-gray-700 rounded-xl p-4"><select value={periodo} onChange={e=>setPeriodo(e.target.value)} className="bg-gray-900 border border-gray-700 rounded-lg p-3"><option value="todos">Todo o período</option><option value="30">Últimos 30 dias</option><option value="90">Últimos 3 meses</option><option value="180">Últimos 6 meses</option><option value="365">Último ano</option></select><select value={equipamento} onChange={e=>setEquipamento(e.target.value)} className="bg-gray-900 border border-gray-700 rounded-lg p-3"><option value="todos">Todos os equipamentos</option>{equipamentos.map(e=><option key={e} value={e}>{e}</option>)}</select><select value={tipo} onChange={e=>setTipo(e.target.value)} className="bg-gray-900 border border-gray-700 rounded-lg p-3"><option value="todos">Todos os tipos de parada</option><option value="nao_programada">Não programada</option><option value="programada">Programada</option><option value="sem_parada">Sem parada</option><option value="nao_informado">Não informado</option></select></section>
 <section className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{[['Ocorrências',lista.length],['Paradas não programadas',d.np],['Downtime total',fmt(d.downtime)],['MTTR',fmt(d.mttr)]].map(([t,v])=><div key={String(t)} className="bg-gray-800 border border-gray-700 rounded-xl p-5"><p className="text-xs uppercase text-gray-400 font-semibold">{t}</p><p className="text-2xl font-bold text-yellow-400 mt-2">{v}</p></div>)}</section><p className="text-xs text-gray-500">Downtime e MTTR usam somente paradas não programadas com início e retorno preenchidos.</p>
 <section className="grid lg:grid-cols-2 gap-5">
 <Grafico titulo="🔧 Ocorrências por equipamento" descricao="Quantidade de registros de manutenção por equipamento."><BarChart data={top} margin={{bottom:55}}><CartesianGrid strokeDasharray="3 3" stroke="#475569"/><XAxis dataKey="nome" angle={-25} textAnchor="end" interval={0} height={70} tick={{fill:'#cbd5e1',fontSize:11}}/><YAxis allowDecimals={false} tick={{fill:'#cbd5e1'}}/><Tooltip/><Legend/><Bar dataKey="ocorrencias" name="Ocorrências">{top.map((_,i)=><Cell key={i} fill={CORES[i%CORES.length]}/>)}</Bar></BarChart></Grafico>
 <Grafico titulo="⏱️ Downtime por equipamento" descricao="Horas de indisponibilidade por parada não programada concluída."><BarChart data={topDt} margin={{bottom:55}}><CartesianGrid strokeDasharray="3 3" stroke="#475569"/><XAxis dataKey="nome" angle={-25} textAnchor="end" interval={0} height={70} tick={{fill:'#cbd5e1',fontSize:11}}/><YAxis tick={{fill:'#cbd5e1'}}/><Tooltip formatter={(v:number)=>fmt(v)}/><Legend/><Bar dataKey="downtime" name="Downtime (horas)">{topDt.map((_,i)=><Cell key={i} fill={CORES[i%CORES.length]}/>)}</Bar></BarChart></Grafico>
 <Grafico titulo="📈 Evolução mensal das ocorrências" descricao="Tendência da quantidade de ocorrências registradas ao longo dos meses."><LineChart data={d.meses}><CartesianGrid strokeDasharray="3 3" stroke="#475569"/><XAxis dataKey="mes" tick={{fill:'#cbd5e1'}}/><YAxis allowDecimals={false} tick={{fill:'#cbd5e1'}}/><Tooltip/><Legend/><Line type="monotone" dataKey="ocorrencias" name="Ocorrências" stroke="#3b82f6" strokeWidth={3}/></LineChart></Grafico>
 <Grafico titulo="📉 Evolução mensal do downtime" descricao="Evolução das horas de indisponibilidade não programada por mês."><LineChart data={d.meses}><CartesianGrid strokeDasharray="3 3" stroke="#475569"/><XAxis dataKey="mes" tick={{fill:'#cbd5e1'}}/><YAxis tick={{fill:'#cbd5e1'}}/><Tooltip formatter={(v:number)=>fmt(v)}/><Legend/><Line type="monotone" dataKey="downtime" name="Downtime (horas)" stroke="#ef4444" strokeWidth={3}/></LineChart></Grafico>
 <Grafico titulo="⚠️ Ocorrências por sintoma" descricao="Distribuição das ocorrências conforme palavras-chave identificadas no sintoma."><BarChart data={d.sintomas} margin={{bottom:65}}><CartesianGrid strokeDasharray="3 3" stroke="#475569"/><XAxis dataKey="nome" angle={-25} textAnchor="end" interval={0} height={80} tick={{fill:'#cbd5e1',fontSize:10}}/><YAxis allowDecimals={false} tick={{fill:'#cbd5e1'}}/><Tooltip/><Legend/><Bar dataKey="valor" name="Ocorrências">{d.sintomas.map((_,i)=><Cell key={i} fill={CORES[i%CORES.length]}/>)}</Bar></BarChart></Grafico>
 <Grafico titulo="🛠️ Ações de manutenção" descricao="Classificação automática das soluções registradas por tipo de ação."><BarChart data={d.acoes} margin={{bottom:55}}><CartesianGrid strokeDasharray="3 3" stroke="#475569"/><XAxis dataKey="nome" angle={-20} textAnchor="end" interval={0} height={70} tick={{fill:'#cbd5e1',fontSize:10}}/><YAxis allowDecimals={false} tick={{fill:'#cbd5e1'}}/><Tooltip/><Legend/><Bar dataKey="valor" name="Ocorrências">{d.acoes.map((_,i)=><Cell key={i} fill={CORES[(i+3)%CORES.length]}/>)}</Bar></BarChart></Grafico>
 </section>
 <section className="bg-gradient-to-br from-gray-800 to-gray-900 border border-gray-700 rounded-2xl p-5 shadow-xl overflow-x-auto">
 <div className="mb-5"><h2 className="font-bold text-xl text-yellow-400">🏆 Ranking de equipamentos</h2><p className="text-xs text-gray-400 mt-1">Comparativo dos equipamentos conforme as ocorrências do período selecionado.</p></div>
 <table className="w-full text-sm min-w-[760px] border-separate border-spacing-y-2"><thead><tr><th className="text-left p-3 rounded-l-lg bg-slate-700 text-slate-100">Equipamento</th><th className="text-center p-3 bg-blue-950 text-blue-300">Ocorrências</th><th className="text-center p-3 bg-orange-950 text-orange-300">Não programadas</th><th className="text-center p-3 bg-red-950 text-red-300">Downtime</th><th className="text-center p-3 rounded-r-lg bg-emerald-950 text-emerald-300">MTTR</th></tr></thead>
 <tbody>{d.ranking.map((r,i)=><tr key={r.nome} className="bg-gray-800/80 hover:bg-gray-700/90 transition"><td className="p-3 rounded-l-lg font-semibold text-white"><span className="text-gray-500 mr-2">#{i+1}</span>{r.nome}</td><td className="p-3 text-center font-bold text-blue-300 bg-blue-950/20">{r.ocorrencias}</td><td className="p-3 text-center font-bold text-orange-300 bg-orange-950/20">{r.naoProgramadas}</td><td className="p-3 text-center font-bold text-red-300 bg-red-950/20">{fmt(r.downtime)}</td><td className="p-3 text-center font-bold text-emerald-300 bg-emerald-950/20 rounded-r-lg">{fmt(r.mttr)}</td></tr>)}</tbody></table>
 <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-2 mt-5 text-xs"><div className="bg-blue-950/30 border border-blue-900 p-3 rounded-lg text-blue-200"><strong>Ocorrências:</strong> total de registros do equipamento.</div><div className="bg-orange-950/30 border border-orange-900 p-3 rounded-lg text-orange-200"><strong>Não programadas:</strong> falhas classificadas como parada não programada.</div><div className="bg-red-950/30 border border-red-900 p-3 rounded-lg text-red-200"><strong>Downtime:</strong> tempo total de indisponibilidade calculável.</div><div className="bg-emerald-950/30 border border-emerald-900 p-3 rounded-lg text-emerald-200"><strong>MTTR:</strong> tempo médio das paradas não programadas concluídas.</div></div>
 </section>
 </div></main>;
}
function Grafico({titulo,descricao,children}:{titulo:string;descricao:string;children:React.ReactElement}){return <div className="bg-gradient-to-br from-gray-800 to-gray-900 border border-gray-700 rounded-2xl p-5 shadow-lg"><h2 className="font-bold text-base text-white">{titulo}</h2><p className="text-xs text-gray-400 mt-1 mb-4">{descricao}</p><div className="h-80"><ResponsiveContainer width="100%" height="100%">{children}</ResponsiveContainer></div></div>;}
